from fastapi.testclient import TestClient

from backend.app.main import app
from backend.app.security.rate_limit_detector import (
    rate_limit_tracker,
    reset_rate_limit,
)


client = TestClient(app)


def setup_function():
    """
    Reset the in-memory rate-limit tracker before each test.
    """

    reset_rate_limit()

    rate_limit_tracker.config.max_requests = 3
    rate_limit_tracker.config.window_seconds = 60.0


def teardown_function():
    """
    Restore the default rate-limit configuration.
    """

    reset_rate_limit()

    rate_limit_tracker.config.max_requests = 10
    rate_limit_tracker.config.window_seconds = 60.0


def get_rate_limit_alert_ids():
    """
    Return the IDs of all currently stored RATE_LIMIT alerts.
    """

    alerts = client.get("/alerts").json()

    return {
        alert["id"]
        for alert in alerts
        if alert["alert_type"] == "RATE_LIMIT"
    }


def test_rate_limit_not_triggered_within_threshold():
    """
    Requests within the configured threshold should not
    create a new RATE_LIMIT alert.
    """

    before_ids = get_rate_limit_alert_ids()

    for index in range(3):
        payload = {
            "event_id": f"integration-rate-ok-{index}",
            "timestamp": 12604154840000 + index,
            "src_ip": "127.0.0.1",
            "dst_ip": "127.0.0.1",
            "src_port": 52000 + index,
            "dst_port": 9000,
            "protocol": "TCP",
            "packet_len": 512,
            "method": "GET",
            "path": "/api/profile",
            "user_id": "integrationUser",
            "role": "USER",
            "object_id": None,
        }

        response = client.post(
            "/events",
            json=payload,
        )

        assert response.status_code == 201

    after_ids = get_rate_limit_alert_ids()

    new_ids = after_ids - before_ids

    assert new_ids == set()


def test_rate_limit_triggered_through_events_api():
    """
    Exceeding the configured threshold through POST /events
    should create a RATE_LIMIT alert.
    """

    before_ids = get_rate_limit_alert_ids()

    for index in range(4):
        payload = {
            "event_id": f"integration-rate-limit-{index}",
            "timestamp": 12604154841000 + index,
            "src_ip": "127.0.0.1",
            "dst_ip": "127.0.0.1",
            "src_port": 53000 + index,
            "dst_port": 9000,
            "protocol": "TCP",
            "packet_len": 512,
            "method": "GET",
            "path": "/api/profile",
            "user_id": "integrationUser",
            "role": "USER",
            "object_id": None,
        }

        response = client.post(
            "/events",
            json=payload,
        )

        assert response.status_code == 201

    after_ids = get_rate_limit_alert_ids()

    new_ids = after_ids - before_ids

    assert len(new_ids) == 1

    new_alert_id = new_ids.pop()

    alerts = client.get("/alerts").json()

    alert = next(
        item
        for item in alerts
        if item["id"] == new_alert_id
    )

    assert alert["alert_type"] == "RATE_LIMIT"
    assert alert["severity"] == "MEDIUM"
    assert alert["destination"] == "/api/profile"


def test_rate_limit_alert_contains_expected_evidence():
    """
    The RATE_LIMIT alert generated by this test should contain
    the expected request-count and threshold evidence.
    """

    before_ids = get_rate_limit_alert_ids()

    for index in range(4):
        payload = {
            "event_id": f"integration-rate-evidence-{index}",
            "timestamp": 12604154842000 + index,
            "src_ip": "127.0.0.1",
            "dst_ip": "127.0.0.1",
            "src_port": 54000 + index,
            "dst_port": 9000,
            "protocol": "TCP",
            "packet_len": 512,
            "method": "GET",
            "path": "/api/profile",
            "user_id": "evidenceUser",
            "role": "USER",
            "object_id": None,
        }

        response = client.post(
            "/events",
            json=payload,
        )

        assert response.status_code == 201

    after_ids = get_rate_limit_alert_ids()

    new_ids = after_ids - before_ids

    assert len(new_ids) == 1

    new_alert_id = new_ids.pop()

    alerts = client.get("/alerts").json()

    alert = next(
        item
        for item in alerts
        if item["id"] == new_alert_id
    )

    assert alert["alert_type"] == "RATE_LIMIT"
    assert alert["severity"] == "MEDIUM"
    assert alert["destination"] == "/api/profile"

    evidence = alert["evidence"]

    assert "request_count" in evidence
    assert "max_requests" in evidence
    assert "window_seconds" in evidence