from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String

from .database import Base


def utc_now():
    """Return the current UTC time."""
    return datetime.now(timezone.utc)


class Event(Base):
    """
    Stores telemetry events received from the eBPF collector.

    The network fields form the stable Member 1 -> Member 2 contract.

    API/security fields are optional and reserved for future
    enrichment and mock-service integration.
    """

    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)

    # Stable external event identifier from Member 1.
    event_id = Column(
        String,
        nullable=False,
        index=True,
    )

    # Kernel/collector timestamp.
    timestamp = Column(
        Integer,
        nullable=False,
    )

    # Stable network telemetry.
    src_ip = Column(String, nullable=False)
    dst_ip = Column(String, nullable=False)

    src_port = Column(Integer, nullable=False)
    dst_port = Column(Integer, nullable=False)

    protocol = Column(String, nullable=False)

    packet_len = Column(Integer, nullable=False)

    # Optional API/application context.
    method = Column(String, nullable=True)
    path = Column(String, nullable=True)

    user_id = Column(String, nullable=True)
    role = Column(String, nullable=True)
    object_id = Column(String, nullable=True)


class Inventory(Base):
    """
    Stores observed network services / APIs.
    """

    __tablename__ = "inventory"

    id = Column(Integer, primary_key=True, index=True)

    # Future HTTP/API information.
    path = Column(String, nullable=True)
    method = Column(String, nullable=True)

    # Current packet-level information.
    dst_ip = Column(String, nullable=True)
    dst_port = Column(Integer, nullable=True)
    protocol = Column(String, nullable=True)

    # Observation timestamps.
    first_seen = Column(
        DateTime,
        default=utc_now,
        nullable=False,
    )

    last_seen = Column(
        DateTime,
        default=utc_now,
        nullable=False,
    )

    request_count = Column(
        Integer,
        default=0,
        nullable=False,
    )

    documented = Column(
        Boolean,
        default=False,
        nullable=False,
    )


class Alert(Base):
    """
    Stores security detection alerts generated by
    BOLA, BFLA, and Shadow API detectors.
    """

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)

    alert_type = Column(String, nullable=False)
    severity = Column(String, nullable=False)

    src_ip = Column(String, nullable=True)
    destination = Column(String, nullable=True)

    timestamp = Column(
        DateTime,
        default=utc_now,
        nullable=False,
    )

    description = Column(String, nullable=False)

    # Detection evidence stored as JSON text.
    evidence = Column(String, nullable=True)

    status = Column(
        String,
        default="OPEN",
        nullable=False,
    )